--- # play example
- hosts: all
  become: yes
  tasks:
    - name: edit host file
      lineinfile:
        path: /etc/hosts
        line: "169.168.0.1 ansible.xyzcorp.com"
    - name: install elinks
      apt:
        name: elinks
        state: latest
    - name: Create audit user
      user:
        name: xyzcorp_network
        state: present
    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: /etc/
      with_items:
        - /home/ansible/motd
        - /home/ansible/issue

- hosts: sysadmin
  become: yes
  tasks:
    - name: Copy tarball
      copy:
        src: /home/ansible/scripts.tgz
        dest: /mnt/storage
